
#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define TERM_WIDTH 80
#define TERM_HEIGHT 25 //hyperterminal resolution

#define WINNING_SOUND 0x02
#define BRICK_COLLISION_SOUND 0x00
#define BORDER_COLLISION_SOUND 0x00
#define STRIKER_COLLISION_SOUND 0x00
#define DEATH_SOUND 0x01

#define true 1
#define false 0
enum { BALL, STRIKER, BRICK, POWERUP, HORIZONTAL_BORDER, VERTICAL_BORDER, BOTTOM_BORDER, ALL_BORDERS };
#endif
